In [5]:
# Importing dependencies
import pandas as pd
#import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import tensorflow as tf
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [7]:
#pip install tensorflow

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
import pandas as pd

In [13]:
# Load the crypto_data.csv dataset.
file_path=("../Stroke-Prediction-Analysis/healthcare-dataset-stroke-data.csv")
stroke_df= pd.read_csv(file_path)
print(stroke_df.shape)
stroke_df.head(10)

(5110, 12)


id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   
5  56669    Male  81.0             0              0          Yes   
6  53882    Male  74.0             1              1          Yes   
7  10434  Female  69.0             0              0           No   
8  27419  Female  59.0             0              0          Yes   
9  60491  Female  78.0             0              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   
5        Private          Urban             186.21  29.0  formerly smoked   
6        Private          Rural              70.09  27.4     never smoked   
7        Private          Urban              94.39  22.8     never smoked   
8        Private          Rural              76.15   NaN          Unknown   
9        Private          Urban              58.57  24.2          Unknown   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       1  
8       1  
9       1

In [14]:
# Remove "ID" column
stroke_all_df= stroke_df.drop("id",axis=1)
stroke_all_df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             202.21   NaN     never smoked       1  
2          Rural             105.92  32.5     never smoked       1  
3          Urban             171.23  34.4           smokes       1  
4          Rural             174.12  24.0     never smoked       1

In [15]:
# Rename Column Names
column =["Gender","Age","Hypertension","Heart_Disease","Ever_Married","Work_Type","Residence_Type","Average_Glucose","BMI","Smoking_Status","Stroke"]
stroke_all_df.columns=column
stroke_all_df.head()

Gender   Age  Hypertension  Heart_Disease Ever_Married      Work_Type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   

  Residence_Type  Average_Glucose   BMI   Smoking_Status  Stroke  
0          Urban           228.69  36.6  formerly smoked       1  
1          Rural           202.21   NaN     never smoked       1  
2          Rural           105.92  32.5     never smoked       1  
3          Urban           171.23  34.4           smokes       1  
4          Rural           174.12  24.0     never smoked       1

In [16]:
# Look for NAN
stroke_all_df.isnull().values.sum()

201

In [17]:
# NAN count in each column
stroke_all_df[column].isnull().sum()

Gender               0
Age                  0
Hypertension         0
Heart_Disease        0
Ever_Married         0
Work_Type            0
Residence_Type       0
Average_Glucose      0
BMI                201
Smoking_Status       0
Stroke               0
dtype: int64

In [18]:
# Drop BMI NAN values from stroke_all_df
stroke_df = stroke_all_df.dropna()

In [19]:
# NAN count in the new dataframe stroke_df
stroke_df[column].isnull().sum()

Gender             0
Age                0
Hypertension       0
Heart_Disease      0
Ever_Married       0
Work_Type          0
Residence_Type     0
Average_Glucose    0
BMI                0
Smoking_Status     0
Stroke             0
dtype: int64

In [20]:
# Shape of the new dataframe stroke_df
stroke_df.shape

(4909, 11)

In [21]:
# Look for datatypes
stroke_df.dtypes

Gender              object
Age                float64
Hypertension         int64
Heart_Disease        int64
Ever_Married        object
Work_Type           object
Residence_Type      object
Average_Glucose    float64
BMI                float64
Smoking_Status      object
Stroke               int64
dtype: object

In [22]:
# Storing the stroke_df with NaN rows removed as a separate CSV
stroke_df.to_csv("stroke_no_NaN.csv")

In [23]:
# Looking at value counts for Gender column
stroke_df["Gender"].value_counts()


Female    2897
Male      2011
Other        1
Name: Gender, dtype: int64

In [24]:
# Deleting row with "Other" value in Gender column
stroke_df=stroke_df[stroke_df.Gender!= "Other"]

In [25]:
# Checking Gender valuecount
stroke_df["Gender"].value_counts()

Female    2897
Male      2011
Name: Gender, dtype: int64

In [26]:
stroke_df

Gender   Age  Hypertension  Heart_Disease Ever_Married      Work_Type  \
0       Male  67.0             0              1          Yes        Private   
2       Male  80.0             0              1          Yes        Private   
3     Female  49.0             0              0          Yes        Private   
4     Female  79.0             1              0          Yes  Self-employed   
5       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
5104  Female  13.0             0              0           No       children   
5106  Female  81.0             0              0          Yes  Self-employed   
5107  Female  35.0             0              0          Yes  Self-employed   
5108    Male  51.0             0              0          Yes        Private   
5109  Female  44.0             0              0          Yes       Govt_job   

     Residence_Type  Average_Glucose   BMI   Smoking_Status  Stroke  
0             Urban           228.69  36.6  formerly smoked       1  
2             Rural           105.92  32.5     never smoked       1  
3             Urban           171.23  34.4           smokes       1  
4             Rural           174.12  24.0     never smoked       1  
5             Urban           186.21  29.0  formerly smoked       1  
...             ...              ...   ...              ...     ...  
5104          Rural           103.08  18.6          Unknown       0  
5106          Urban           125.20  40.0     never smoked       0  
5107          Rural            82.99  30.6     never smoked       0  
5108          Rural           166.29  25.6  formerly smoked       0  
5109          Urban            85.28  26.2          Unknown       0  

[4908 rows x 11 columns]

# One Hot Encoding

In [27]:

# Generate our categorical variable lists
stroke_df_cat = stroke_df.dtypes[stroke_df.dtypes == "object"].index.tolist()

In [28]:
# Check the number of unique values in each column
stroke_df[stroke_df_cat].nunique()

Gender            2
Ever_Married      2
Work_Type         5
Residence_Type    2
Smoking_Status    4
dtype: int64

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(stroke_df[stroke_df_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(stroke_df_cat)
encode_df.head()

/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Gender_Female  Gender_Male  Ever_Married_No  Ever_Married_Yes  \
0            0.0          1.0              0.0               1.0   
1            0.0          1.0              0.0               1.0   
2            1.0          0.0              0.0               1.0   
3            1.0          0.0              0.0               1.0   
4            0.0          1.0              0.0               1.0   

   Work_Type_Govt_job  Work_Type_Never_worked  Work_Type_Private  \
0                 0.0                     0.0                1.0   
1                 0.0                     0.0                1.0   
2                 0.0                     0.0                1.0   
3                 0.0                     0.0                0.0   
4                 0.0                     0.0                1.0   

   Work_Type_Self-employed  Work_Type_children  Residence_Type_Rural  \
0                      0.0                 0.0                   0.0   
1                      0.0                 0.0                   1.0   
2                      0.0                 0.0                   0.0   
3                      1.0                 0.0                   1.0   
4                      0.0                 0.0                   0.0   

   Residence_Type_Urban  Smoking_Status_Unknown  \
0                   1.0                     0.0   
1                   0.0                     0.0   
2                   1.0                     0.0   
3                   0.0                     0.0   
4                   1.0                     0.0   

   Smoking_Status_formerly smoked  Smoking_Status_never smoked  \
0                             1.0                          0.0   
1                             0.0                          1.0   
2                             0.0                          0.0   
3                             0.0                          1.0   
4                             1.0                          0.0   

   Smoking_Status_smokes  
0                    0.0  
1                    0.0  
2                    1.0  
3                    0.0  
4                    0.0

In [31]:
# Merge one-hot encoded features and drop the originals
stroke_df = stroke_df.merge(encode_df,left_index=True, right_index=True)
stroke_df = stroke_df.drop(stroke_df_cat,1)
stroke_df.head()

/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


Age  Hypertension  Heart_Disease  Average_Glucose   BMI  Stroke  \
0  67.0             0              1           228.69  36.6       1   
2  80.0             0              1           105.92  32.5       1   
3  49.0             0              0           171.23  34.4       1   
4  79.0             1              0           174.12  24.0       1   
5  81.0             0              0           186.21  29.0       1   

   Gender_Female  Gender_Male  Ever_Married_No  Ever_Married_Yes  ...  \
0            0.0          1.0              0.0               1.0  ...   
2            1.0          0.0              0.0               1.0  ...   
3            1.0          0.0              0.0               1.0  ...   
4            0.0          1.0              0.0               1.0  ...   
5            0.0          1.0              0.0               1.0  ...   

   Work_Type_Never_worked  Work_Type_Private  Work_Type_Self-employed  \
0                     0.0                1.0                      0.0   
2                     0.0                1.0                      0.0   
3                     0.0                0.0                      1.0   
4                     0.0                1.0                      0.0   
5                     0.0                1.0                      0.0   

   Work_Type_children  Residence_Type_Rural  Residence_Type_Urban  \
0                 0.0                   0.0                   1.0   
2                 0.0                   0.0                   1.0   
3                 0.0                   1.0                   0.0   
4                 0.0                   0.0                   1.0   
5                 0.0                   1.0                   0.0   

   Smoking_Status_Unknown  Smoking_Status_formerly smoked  \
0                     0.0                             1.0   
2                     0.0                             0.0   
3                     0.0                             0.0   
4                     0.0                             1.0   
5                     0.0                             0.0   

   Smoking_Status_never smoked  Smoking_Status_smokes  
0                          0.0                    0.0  
2                          0.0                    1.0  
3                          1.0                    0.0  
4                          0.0                    0.0  
5                          1.0                    0.0  

[5 rows x 21 columns]

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
# Split our preprocessed data into our features and target arrays
y = stroke_df["Stroke"].values
X = stroke_df.drop(["Stroke"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [35]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

# Oversampling for X_train_scaled

In [36]:
from collections import Counter

In [37]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(
    X_train, y_train
)
X_resampled_scaled = X_scaler.transform(X_resampled)

X_test_scaled = X_scaler.transform(X_test)
Counter(y_resampled)

Counter({0: 3391, 1: 3391})

# Decision Tree

In [38]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [39]:
# Decision tree will tell us whether or not a person is a potential stroke victim
dt.fit(X_resampled, y_resampled)

DecisionTreeClassifier()

In [40]:
dt.feature_importances_

array([3.65141425e-01, 9.88153155e-02, 2.74459286e-03, 7.39139948e-02,
       3.71889908e-02, 1.11847123e-02, 2.75107008e-03, 1.81738551e-02,
       1.09536941e-01, 1.73060270e-03, 1.81365886e-04, 5.50374600e-02,
       6.96889635e-03, 5.01495555e-03, 1.19541173e-02, 1.39839842e-02,
       2.99734478e-02, 6.68512306e-02, 3.06582064e-02, 5.81948356e-02])

In [44]:
y_pred=dt.predict(X_test)
accuracy_score(y_test, y_pred)

0.8999151823579304

In [45]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1050   65]
 [  53   11]]


In [46]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1115
           1       0.14      0.17      0.16        64

    accuracy                           0.90      1179
   macro avg       0.55      0.56      0.55      1179
weighted avg       0.91      0.90      0.90      1179



In [47]:
import os
import joblib

filename = os.path.join('models/', 'dt3.joblib')
joblib.dump(dt,filename)

['models/dt3.joblib']

In [48]:
joblib.load(filename)

DecisionTreeClassifier()

# PCA

In [49]:
from sklearn.decomposition import PCA

In [50]:
# Initialize PCA model
pca = PCA(n_components=2)

## Get two principal components for the data.
#stroke_pca = pca.fit_transform(stroke_scaled)
stroke_pca = pca.fit_transform(X_resampled_scaled)

In [51]:
# Transform PCA data to a DataFrame
stroke_df_pca = pd.DataFrame(
    data=stroke_pca, columns=["principal component 1", "principal component 2",]
)
stroke_df_pca.head()

principal component 1  principal component 2
0              -0.351486              -0.692405
1              -2.281676              -0.280051
2              -1.428815              -0.000019
3              -1.638586               0.576259
4              -0.648398              -1.261145

In [52]:
# Fetch the explained variance
pca.explained_variance_ratio_

array([0.15328578, 0.10831783])

In [53]:
# Initialize PCA model for 3 principal components
pca = PCA(n_components=10)

# Get two principal components for the iris data.
stroke_pca = pca.fit_transform(X_resampled_scaled)

In [54]:
# Transform PCA data to a DataFrame
stroke_df_pca = pd.DataFrame(
    data=stroke_pca, columns=["principal component 1", "principal component 2", "principal component 3",
                              "principal component 4","principal component 5","principal component 6",
                              "principal component 7","principal component 8", "principal component 9",
                             "principal component 10"]
)
stroke_df_pca.head()

principal component 1  principal component 2  principal component 3  \
0              -0.350282              -0.703493               2.308285   
1              -2.283337              -0.271989              -1.809750   
2              -1.427819              -0.015142              -1.658104   
3              -1.640206               0.569961               2.164042   
4              -0.648245              -1.260715              -1.814734   

   principal component 4  principal component 5  principal component 6  \
0               0.338401              -0.848727               0.053513   
1              -0.409562              -1.066102               0.544343   
2               0.012584              -0.481150              -0.725579   
3               0.927597               1.106278              -0.030458   
4               0.586462               1.127080               0.626861   

   principal component 7  principal component 8  principal component 9  \
0               1.718428               0.124891               0.129884   
1               1.244727              -0.200741               0.728580   
2              -1.024435              -1.182649               1.692520   
3              -0.045800               0.457520              -0.809853   
4               1.416798              -0.136045              -1.155159   

   principal component 10  
0               -0.053570  
1               -0.346907  
2                0.492206  
3                2.409698  
4                2.160571

In [55]:
# Fetch the explained variance
pca.explained_variance_ratio_

array([0.15328585, 0.10832022, 0.09269632, 0.08452705, 0.0776367 ,
       0.07164607, 0.06661738, 0.06467808, 0.05718675, 0.05230711])

In [56]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [57]:
classifier.fit(X_resampled, y_resampled)

/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(max_iter=200, random_state=1)

In [58]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head()

Prediction  Actual
0           0       0
1           0       0
2           0       0
3           0       0
4           0       0

In [59]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7625106022052587


In [60]:
# Display the confusion matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[846 269]
 [ 11  53]]


In [61]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      0.76      0.86      1115
           1       0.16      0.83      0.27        64

    accuracy                           0.76      1179
   macro avg       0.58      0.79      0.57      1179
weighted avg       0.94      0.76      0.83      1179



# Random Forest

In [62]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [63]:
#clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train_scaled, y_train)
rf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_resampled_scaled, y_resampled)
#print(f'Training Score: {clf.score(X_train_scaled, y_train)}')
print(f'Training Score: {rf.score(X_resampled_scaled, y_resampled)}')
print(f'Testing Score: {rf.score(X_test_scaled, y_test)}')

Training Score: 1.0
Testing Score: 0.9440203562340967


In [64]:
feature_importances = rf.feature_importances_
feature_importances

array([0.21864758, 0.11625168, 0.03703195, 0.06293644, 0.04060651,
       0.0337005 , 0.02922794, 0.0637567 , 0.06452371, 0.01521187,
       0.00140493, 0.05097201, 0.0231454 , 0.00715348, 0.04204984,
       0.04094915, 0.05031048, 0.0328193 , 0.04342011, 0.02588043])

In [65]:
from sklearn.metrics import accuracy_score

In [66]:
y_pred=rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.0542832909245123

In [67]:
y_pred = rf.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(5)

Prediction  Actual
0           1       0
1           1       0
2           1       0
3           1       0
4           1       0

In [68]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [69]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   0 1115]
 [   0   64]]


In [70]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00      1115
           1       0.05      1.00      0.10        64

    accuracy                           0.05      1179
   macro avg       0.03      0.50      0.05      1179
weighted avg       0.00      0.05      0.01      1179



/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/bradroberts/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

# Neural Network Model

In [71]:
import tensorflow as tf

In [72]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 168       
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6         
Total params: 219
Trainable params: 219
Non-trainable params: 0
_________________________________________________________________


2022-06-01 14:07:20.773471: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [73]:
# Compile the model and define loss and accuracy
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [74]:

# Train the model
#fit_model = nn.fit(X_train_scaled,y_train,epochs=100)
fit_model = nn.fit(X_resampled_scaled,y_resampled,epochs=100)

2022-06-01 14:07:24.638923: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)


Epoch 1/100
212/212 [==============================] - 1s 1ms/step - loss: 0.7744 - accuracy: 0.4727
Epoch 2/100
212/212 [==============================] - 0s 2ms/step - loss: 0.6043 - accuracy: 0.7188
Epoch 3/100
212/212 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.7933
Epoch 4/100
212/212 [==============================] - 0s 2ms/step - loss: 0.4489 - accuracy: 0.8029
Epoch 5/100
212/212 [==============================] - 0s 1ms/step - loss: 0.4225 - accuracy: 0.8155
Epoch 6/100
212/212 [==============================] - 0s 1ms/step - loss: 0.4059 - accuracy: 0.8168
Epoch 7/100
212/212 [==============================] - 0s 1ms/step - loss: 0.3961 - accuracy: 0.8198
Epoch 8/100
212/212 [==============================] - 0s 1ms/step - loss: 0.3717 - accuracy: 0.8310
Epoch 9/100
212/212 [==============================] - 0s 1ms/step - loss: 0.3693 - accuracy: 0.8375
Epoch 10/100
212/212 [==============================] - 0s 1ms/step - loss: 0.3426 - accura

212/212 [==============================] - 0s 1ms/step - loss: 0.2255 - accuracy: 0.9102
Epoch 82/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2365 - accuracy: 0.9059
Epoch 83/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2244 - accuracy: 0.9098
Epoch 84/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2304 - accuracy: 0.9074
Epoch 85/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2243 - accuracy: 0.9128
Epoch 86/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2210 - accuracy: 0.9176
Epoch 87/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2388 - accuracy: 0.9044
Epoch 88/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2253 - accuracy: 0.9141
Epoch 89/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2336 - accuracy: 0.9068
Epoch 90/100
212/212 [==============================] - 0s 1ms/step - loss: 0.2258 - accuracy: 

In [75]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

37/37 - 0s - loss: 0.3744 - accuracy: 0.8499
Loss: 0.37443795800209045, Accuracy: 0.8498727679252625
